In [86]:
# import time 
# import sys

import numpy as np 

# import matplotlib.pyplot as plt
# %matplotlib inline

![title](image/classify.png)

# Define a list in Python


In [1]:
a=["0",1,"two","3",4]
print(a)

['0', 1, 'two', '3', 4]


![title](image/array.png)

#### We can access each element using a square bracket as follows:

In [4]:
print("a[0]:",a[0])
print("a[1]:",a[1])
print("a[2]:",a[2])
print("a[3]:",a[3])
print("a[4]:",a[4])

a[0]: 0
a[1]: 1
a[2]: two
a[3]: 3
a[4]: 4


In [5]:
import numpy as np
help(np.where)


Help on built-in function where in module numpy.core.multiarray:

where(...)
    where(condition, [x, y])
    
    Return elements, either from `x` or `y`, depending on `condition`.
    
    If only `condition` is given, return ``condition.nonzero()``.
    
    Parameters
    ----------
    condition : array_like, bool
        When True, yield `x`, otherwise yield `y`.
    x, y : array_like, optional
        Values from which to choose. `x`, `y` and `condition` need to be
        broadcastable to some shape.
    
    Returns
    -------
    out : ndarray or tuple of ndarrays
        If both `x` and `y` are specified, the output array contains
        elements of `x` where `condition` is True, and elements from
        `y` elsewhere.
    
        If only `condition` is given, return the tuple
        ``condition.nonzero()``, the indices where `condition` is True.
    
    See Also
    --------
    nonzero, choose
    
    Notes
    -----
    If `x` and `y` are given and input arrays are

In [7]:
x = np.arange(9).reshape(3,3)
print("x:",x)
print('--------------------------------')
y = np.where( x > 5,x,0 )

print(y)


x: [[0 1 2]
 [3 4 5]
 [6 7 8]]
--------------------------------
[[0 0 0]
 [0 0 0]
 [6 7 8]]


#### A numpy array is similar to a list, it's usually fixed in size and each element is of the same type. We can cast a list to a numpy array by first importing numpy:

In [8]:
import numpy as np

a=np.array([0,1,2,3, 4])
print(a)

b = np.array([0,5,12,25,85], dtype=np.float32) 
print(b)
print(b.astype(int)) #change type

[0 1 2 3 4]
[ 0.  5. 12. 25. 85.]
[ 0  5 12 25 85]


#### np.zero
#### np.one
#### np.full
#### np.eye

In [26]:
print(np.zeros(shape=(3,3)))
print("zero:",np.zeros(10))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
zero: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [14]:
print(np.full((2,3),6))
print('----------------------')
print(np.ones(shape=(2,6)))
print('----------------------')
print("eye",np.eye(5))

[[6 6 6]
 [6 6 6]]
----------------------
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
----------------------
eye [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [105]:
import numpy as np
#change item in array 
#for random data in dataset for input
a = np.arange(10)
np.random.shuffle(a)
print(a)

[2 6 5 8 4 1 3 0 7 9]


### Each element is of the same type, in this case integers:
![title](image/nparr.png)

In [15]:
print("a[0]:",a[0])
print("a[1]:",a[1])
print("a[2]:",a[2])
print("a[3]:",a[3])
print("a[4]:",a[4])

a[0]: 0
a[1]: 1
a[2]: 2
a[3]: 3
a[4]: 4


### If we check the type of the array we get "numpy.ndarray":

In [16]:
type(a)

numpy.ndarray

#### As numpy arrays contain data of the same type, we can use the attribute "dtype" to obtain the Data-type of the array’s elements. In this case a 64-bit integer:

In [23]:
print(a.dtype)

int64


### We can change the value of the array, consider the array "c":

In [19]:
c=np.array([20,1,2,3,4])
print(c)
c[0]=55
print(c)

[20  1  2  3  4]
[55  1  2  3  4]


### Like lists, we can slice the numpy array, and we can select the elements from 1 to 3 and assign it to a new numpy array 'd' as follows:

In [26]:
d=c[1:4]
print(d)

[1 2 3]


#### Similarly, we can use a list to select a specific index. The list ' select ' contains several values:
#### We can use the list as an argument in the brackets. The output is the elements corresponding to the particular index:

In [22]:
print(c)
select=[0,2,3]
d=c[select]
print(d)

[55  1  2  3  4]
[55  2  3]


#### Let's review some basic array attributes using the array ‘a’:

In [25]:
a = np.array([2,5,4,56,8,98])
print(a)
print("===========>",len([2,5,6,4,55]))
print("size:",a.size)

[ 2  5  4 56  8 98]
===========> 5
size: 6


#### The next two attributes will make more sense when we get to higher dimensions but let's review them. The attribute “ndim” represents the Number of array dimensions or the rank of the array, in this case, one:



In [34]:
print(a.ndim)


1


In [42]:
a=np.array([1,-1,1,-1])
b = np.array([2,4,6,8])
print(a.mean())
print(b.mean())

0.0
6.0


In [26]:
list = [2,4,6,8]
a =0
for i in list:
    a = a + i
print("mean:",a / len(list))

mean: 5.0


#### standard_deviation

In [50]:
a = np.array([2,4,6,8])
standard_deviation=a.std()
print(standard_deviation)

2.23606797749979


### max

In [31]:
import numpy as np
a = np.array([2,54,45,6,9,6,46,41])
print('numpy:',a.max())
print('python:',max(a))

numpy: 54
python: 54


In [32]:
print("min:",a.min())
print("python:",min(a))

min: 2
python: 2


## Array Addition

In [38]:
u=np.array([1,0])
v=np.array([0,1])
z = u + v
print(z)

[1 1]


### Consider the vector numpy array 'y':

In [62]:
y=np.array([1,2])
z = 2 * y
print(z)

[2 4]


### Product of two numpy arrays

In [40]:
a = np.array([5,10,5,4,56])
b = np.array([5,6,4,22,5])
c = a * b
print(c)

[ 25  60  20  88 280]


In [82]:
a = [5,10,5,4,56]
b = [5,6,4,22,5]
c =[a[i]*b[i] for i in range(len(a))]
print(c)

[25, 60, 20, 88, 280]


## Dot Product
### The dot product of the two numpy arrays 'u' and 'v' is given by:

In [83]:
u = np.array([4,5])
v = np.array([6,7])
print(np.dot(u,v))

59


### Adding Constant to a numpy Array

In [84]:
u=np.array([1,2,3,-1]) 
print(u + 1)

[2 3 4 0]


![title](image/count.gif)

## Mathematical Functions
### We can access the value of pie in numpy as follows :

In [85]:
print(np.pi)

3.141592653589793


### Consider the list a , the list contains three nested lists each of equal size.

In [47]:
import numpy as np

a=[[
    [[2,5,6,9,5]],
   [[2,5,6,9,6]],
   [[31,32,33]]
]]
print('ndim:',np.ndim(a))


A = np.array(a)
print('shape:',A.shape)
print('size:',A.size)



ndim: 3
shape: (1, 3, 1)
size: 3


### Accessing different elements of an Numpy Array¶
We can use rectangular brackets to access the different elements of the array,The correspondence between the rectangular brackets and the list and the rectangular representation is shown in the following figure for a 3x3 array

In [48]:
import numpy as np
a=[[11,12,13],
   [21,22,23],
   [31,32,33]]
B = np.array(a)
print(B[0][0])

11


![title](image/numpy-4.png)

In [26]:
import numpy as np
a=[[11,12,13],
   [21,22,23],
   [31,32,33]]
B = np.array(a)
print(B[1][2])

23


![title](image/numpy-5.png)

In [33]:
import numpy as np
a=[[11,12,13],
   [21,22,23],
   [31,32,33]]
B = np.array(a)
print(B[0][0:2])

[11 12]


![title](image/numpy-7.png)

In [53]:
import numpy as np
a=[[11,12,13],
   [21,22,23],
   [31,32,33]]
B = np.array(a)
print(B[1:3,2])

[23 33]


![title](image/numpy-8.png)

#### Basic Operations
We can also add arrays; the process is identical to matrix addition. Matrix addition of X and Y is shown in the following figure:

![title](image/numpy-9.png)

#### The numpy array is given by X and Y

In [40]:
import numpy as np

x=np.array([[1,0],[0,1]]) 
y=np.array([[2,1],[1,2]]) 
z = x + y
print(z)

[[3 1]
 [1 3]]


 Multiplying a numpy array by a scaler is identical to multiplying a matrix by a scaler. If we multiply the matrix Y by the scaler 2, we simply multiply every element in the matrix by 2 as shown in the figure

![title](image/numpy-10.png)

In [42]:
import numpy as np
y=np.array([[2,1],
            [1,2]
           ]) 
z = 2 * y
print(z)

[[4 2]
 [2 4]]


Multiplication of two arrays corresponds to an element-wise product or Hadamard product. Consider matrix X and Y. The Hadamard product corresponds to multiplying each of the elements in the same position, i.e. multiplying elements contained in the same colour boxes together. The result is a new matrix that is the same size as matrix Y or X, as shown in the following figure.

![title](image/numpy-11.png)

In [44]:
import numpy as np

x=np.array([[1,0],[0,1]]) 
y=np.array([[2,1],[1,2]]) 
z = x * y
print(z)

[[2 0]
 [0 2]]


### About the Authors:

![title](image/joseph.jpg)

Joseph Santarcangelo has a PhD in Electrical Engineering, his research focused on using machine learning, signal processing, and computer vision to determine how videos impact human cognition. Joseph has been working for IBM since he completed his PhD.

Copyright © 2017 cognitiveclass.ai. This notebook and its source code are released under the terms of the MIT License.